from filter import RangeFilter, TemporalMedianFilter
from robot import Robot

if __name__ == '__main__':
    robot = Robot()

    samples_generated = robot.generate_scan(7, 400)

    print 'Samples generated by the scan : '

    for i in range(len(samples_generated)):
        print samples_generated[i]

    range_filter = RangeFilter([2, 25])

    filtered_samples_by_range = range_filter.filter(samples_generated)

    print 'Filtered samples : '

    for i in range(len(filtered_samples_by_range)):
        print filtered_samples_by_range[i]

    temporal_median_filter = TemporalMedianFilter(4)

    print 'Temporal filtered samples : '

    temporal_filtered_samples = temporal_median_filter.filter(samples_generated)

    for i in range(len(temporal_filtered_samples)):
        print temporal_filtered_samples[i]

    test_sample = [[0, 1, 2, 1, 3], [1, 5, 7, 1, 3], [2, 3, 4, 1, 0], [3, 3, 3, 1, 3], [10, 2, 4, 0, 0]]

    print 'Test sample'

    for i in range(len(test_sample)):
        print test_sample[i]

    test_temporal_median_filter = TemporalMedianFilter(3)

    test_temporal_filtered_samples = test_temporal_median_filter.filter(test_sample)

    print 'Test Temporal filtered samples : '

    for i in range(len(test_temporal_filtered_samples)):
        print test_temporal_filtered_samples[i]
