from filter import RangeFilter, TemporalMedianFilter
from robot import Robot
import argparse

runner_parser = argparse.ArgumentParser(
    description='This parser parses command line arguments for the runner.py script')

runner_parser.add_argument('--num_samples', type=int, default=30)
runner_parser.add_argument('--sample_size', type=int, default=20)

if __name__ == '__main__':

    parsed_arguments = runner_parser.parse_args()

    robot = Robot()

    samples_generated = robot.generate_scan(parsed_arguments.num_samples, parsed_arguments.sample_size)

    print 'Samples generated by the scan : '

    for i in range(len(samples_generated)):
        print samples_generated[i]

    range_filter = RangeFilter([2, 25])

    filtered_samples_by_range = range_filter.filter(samples_generated)

    print 'Filtered samples : '

    for i in range(len(filtered_samples_by_range)):
        print filtered_samples_by_range[i]

    temporal_median_filter = TemporalMedianFilter(4)

    print 'Temporal filtered samples : '

    temporal_filtered_samples = temporal_median_filter.filter(samples_generated)

    for i in range(len(temporal_filtered_samples)):
        print temporal_filtered_samples[i]
